/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mapleworld.game.tapgame.gui;

import com.alee.laf.WebLookAndFeel;
import com.mapleworld.game.tapgame.main.TapGame;
import com.mapleworld.game.tapgame.tools.SQLiteJDBCUtils;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import java.awt.*;
import java.sql.SQLException;
import java.util.List;
import java.util.Optional;

/**
 *
 * @author zzl55
 */
public class NewGameGui extends javax.swing.JFrame {
static GameMainGui gameMainGui;
SQLiteJDBCUtils.PlayerData playerdata;
    boolean [] playerPos = {false,false,false};


    /**
     * Creates new form NewGame
     */
    public NewGameGui() {
        initComponents();
        initSaveJP();
        selectMod1.setVisible(false);
        selectMod2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        selectMod1 = new javax.swing.JPanel();
        btMod1_0 = new javax.swing.JButton();
        btMod1_1 = new javax.swing.JButton();
        btSetting = new javax.swing.JButton();
        btAbout = new javax.swing.JButton();
        btExit = new javax.swing.JButton();
        saveSelect = new javax.swing.JPanel();
        btSave1 = new javax.swing.JButton();
        btSave2 = new javax.swing.JButton();
        btSave3 = new javax.swing.JButton();
        selectMod2 = new javax.swing.JPanel();
        btMod2_0 = new javax.swing.JButton();
        btMod2_1 = new javax.swing.JButton();
        btMod2_2 = new javax.swing.JButton();
        btMod2_back = new javax.swing.JButton();
        lbLoad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 36)); // NOI18N
        jLabel1.setText("打字游戏");

        selectMod1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "$Player-变更存档", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei UI", 0, 10))); // NOI18N
        selectMod1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectMod1MouseClicked(evt);
            }
        });

        btMod1_0.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 10)); // NOI18N
        btMod1_0.setText("单人模式");
        btMod1_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMod1_0ActionPerformed(evt);
            }
        });

        btMod1_1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 10)); // NOI18N
        btMod1_1.setText("两人联机");
        btMod1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMod1_1ActionPerformed(evt);
            }
        });

        btSetting.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 10)); // NOI18N
        btSetting.setText("统计");
        btSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSettingActionPerformed(evt);
            }
        });

        btAbout.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 10)); // NOI18N
        btAbout.setText("设置");
        btAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAboutActionPerformed(evt);
            }
        });

        btExit.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 10)); // NOI18N
        btExit.setText("退出");
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout selectMod1Layout = new javax.swing.GroupLayout(selectMod1);
        selectMod1.setLayout(selectMod1Layout);
        selectMod1Layout.setHorizontalGroup(
            selectMod1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectMod1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(selectMod1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btMod1_0, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(btMod1_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btSetting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btAbout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        selectMod1Layout.setVerticalGroup(
            selectMod1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectMod1Layout.createSequentialGroup()
                .addComponent(btMod1_0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btMod1_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSetting)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAbout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        saveSelect.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "选择存档", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei UI", 0, 10))); // NOI18N
        saveSelect.setToolTipText("");
        saveSelect.setName("测"); // NOI18N

        btSave1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 10)); // NOI18N
        btSave1.setText("+新玩家");
        btSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSave1ActionPerformed(evt);
            }
        });

        btSave2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 10)); // NOI18N
        btSave2.setText("+新玩家");
        btSave2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSave2ActionPerformed(evt);
            }
        });

        btSave3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 10)); // NOI18N
        btSave3.setText("+新玩家");
        btSave3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSave3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout saveSelectLayout = new javax.swing.GroupLayout(saveSelect);
        saveSelect.setLayout(saveSelectLayout);
        saveSelectLayout.setHorizontalGroup(
            saveSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saveSelectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(saveSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btSave1, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(btSave2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btSave3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        saveSelectLayout.setVerticalGroup(
            saveSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saveSelectLayout.createSequentialGroup()
                .addComponent(btSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSave2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSave3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        btMod2_0.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 10)); // NOI18N
        btMod2_0.setText("$Mod2Name0");
        btMod2_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMod2_0ActionPerformed(evt);
            }
        });

        btMod2_1.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 10)); // NOI18N
        btMod2_1.setText("$Mod2Name1");
        btMod2_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMod2_1ActionPerformed(evt);
            }
        });

        btMod2_2.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 10)); // NOI18N
        btMod2_2.setText("$Mod2Name2");
        btMod2_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMod2_2ActionPerformed(evt);
            }
        });

        btMod2_back.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 10)); // NOI18N
        btMod2_back.setText("←返回");

        javax.swing.GroupLayout selectMod2Layout = new javax.swing.GroupLayout(selectMod2);
        selectMod2.setLayout(selectMod2Layout);
        selectMod2Layout.setHorizontalGroup(
            selectMod2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, selectMod2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(selectMod2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btMod2_back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btMod2_0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btMod2_1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btMod2_2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );
        selectMod2Layout.setVerticalGroup(
            selectMod2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectMod2Layout.createSequentialGroup()
                .addComponent(btMod2_0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btMod2_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btMod2_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btMod2_back)
                .addGap(0, 37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(saveSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectMod1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectMod2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectMod1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectMod2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbLoad.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        lbLoad.setText("Loading...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(lbLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btMod1_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMod1_0ActionPerformed
        //gameMainGui.main();
        TapGame.setPlayerData(playerdata);
        TapGame.newGame(0,0,playerdata.getDifficult());
    }//GEN-LAST:event_btMod1_0ActionPerformed

    private void btSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSave1ActionPerformed
        if(playerPos[0]){
            playerdata = new SQLiteJDBCUtils().selectPlayerInfo(1,false);
            saveSelect.setVisible(false);
            selectMod1.setVisible(true);
            selectMod1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, playerdata.getPlayerName() + "-变更存档", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei UI", 0, 10))); // NOI18N
            selectMod1.setVisible(true);
        }else{
            newPlayer(1);
        }

    }//GEN-LAST:event_btSave1ActionPerformed

    private void btSave2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSave2ActionPerformed
        if(playerPos[1]){
            playerdata = new SQLiteJDBCUtils().selectPlayerInfo(2,false);
            saveSelect.setVisible(false);
            selectMod1.setVisible(true);
            selectMod1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, playerdata.getPlayerName() + "-变更存档", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei UI", 0, 10))); // NOI18N
            selectMod1.setVisible(true);
        }else{
            newPlayer(2);
        }
    }//GEN-LAST:event_btSave2ActionPerformed

    private void btSave3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSave3ActionPerformed
        if(playerPos[2]){
            playerdata = new SQLiteJDBCUtils().selectPlayerInfo(3,false);
            saveSelect.setVisible(false);
            selectMod1.setVisible(true);
            selectMod1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, playerdata.getPlayerName() + "-变更存档", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei UI", 0, 10))); // NOI18N
            selectMod1.setVisible(true);
        }else{
            newPlayer(3);
        }
    }//GEN-LAST:event_btSave3ActionPerformed

    private void btMod1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMod1_1ActionPerformed
        CreateMPRoom cmr = new CreateMPRoom();
    }//GEN-LAST:event_btMod1_1ActionPerformed

    private void btSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSettingActionPerformed
        StatisticsGui sgui = new StatisticsGui();
        sgui.UI_GameOver_setInfo(playerdata.getId());
        sgui.setVisible(true);
    }//GEN-LAST:event_btSettingActionPerformed

    private void btAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAboutActionPerformed
        SettingGui settingGui = new SettingGui();
        settingGui.setInfo(playerdata.getId());
        settingGui.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btAboutActionPerformed

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btExitActionPerformed

    private void btMod2_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMod2_0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btMod2_0ActionPerformed

    private void btMod2_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMod2_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btMod2_1ActionPerformed

    private void btMod2_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMod2_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btMod2_2ActionPerformed

    private void selectMod1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectMod1MouseClicked
        selectMod1.setVisible(false);
        initSaveJP();
    }//GEN-LAST:event_selectMod1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        WebLookAndFeel.install ();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>
        //</editor-fold>
        UIManager.put("OptionPane.buttonFont", new FontUIResource(new Font("Microsoft YaHei UI", Font.PLAIN, 10)));
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font("Microsoft YaHei UI", Font.PLAIN, 10)));
        //UIManager.put("TextField.Font", new FontUIResource(new Font("Microsoft YaHei UI", Font.PLAIN, 10)));
        UIManager.put("TextField.font",new Font("Microsoft YaHei UI", Font.PLAIN, 10));

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewGameGui().setVisible(true);
            }
        });
        
    }

    public void initSaveJP(){
        lbLoad.setVisible(true);
        saveSelect.setVisible(false);
        JButton saveBTList[] = {btSave1,btSave2,btSave3};
        try {
            List<SQLiteJDBCUtils.PlayerData> playerdataTp;
            for(int i = 1;i <= 3;i ++) {
                playerdataTp = new SQLiteJDBCUtils().selectPlayerInfo(i);
                if(playerdataTp.size() > 0){
                    //playerdata.add(playerdataTp.get(0));
                    playerPos[i-1] = true;
                    String playerName = playerdataTp.get(0).getPlayerName();
                    int playTime = playerdataTp.get(0).getPlayTime();
                    saveBTList[i-1].setText("<html>" + playerName + "<br>" + (int)Math.ceil(playTime/60) + "分钟</html>");
                }
            }
        } catch (SQLException e) {
            System.err.println("读取玩家数据出错。"+e);
        }
        saveSelect.setVisible(true);
        lbLoad.setVisible(false);

    }

    public void newPlayer(int pos){
        String inputName = JOptionPane.showInputDialog("请输入玩家名：");
        if(inputName == null){
            return;
        }
        try{
            new SQLiteJDBCUtils().savePlayerInfo(pos,inputName,0,0,0,0,0);
        }catch (SQLException e) {
            System.err.println("保存玩家数据出错。"+e);
        }
        initSaveJP();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAbout;
    private javax.swing.JButton btExit;
    private javax.swing.JButton btMod1_0;
    private javax.swing.JButton btMod1_1;
    private javax.swing.JButton btMod2_0;
    private javax.swing.JButton btMod2_1;
    private javax.swing.JButton btMod2_2;
    private javax.swing.JButton btMod2_back;
    private javax.swing.JButton btSave1;
    private javax.swing.JButton btSave2;
    private javax.swing.JButton btSave3;
    private javax.swing.JButton btSetting;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbLoad;
    private javax.swing.JPanel saveSelect;
    private javax.swing.JPanel selectMod1;
    private javax.swing.JPanel selectMod2;
    // End of variables declaration//GEN-END:variables
}
